name: Build and test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  qa:
    name: Run QA checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'
      - name: Install dependencies
        shell: bash
        run: pip install -r dev-requirements.txt
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3
        with:
          cache: true
      - name: Run MATLAB code analyser
        uses: matlab-actions/run-build@v3
        with:
          tasks: check
          startup-options: -nojvm
          generate-summary: true
      - name: Run pre-commit hooks
        shell: bash
        run: SKIP=codeIssues pre-commit run --all-files
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3
        with:
          cache: true
      - name: Run MATLAB unit and regression tests
        uses: matlab-actions/run-build@v3
        with:
          tasks: test-unit test-regression
          startup-options: -nojvm
          generate-summary: true
